device: 'cuda:0'
dataloader:
  celebA: "../celeba/"
  download: False
  target_type: "attr"
training:
    n_epoch: 10
    log_step: 1000
    save_step: 1000
    sample_step: 1000
    batch_size: 16
    D:
        betas: [0.5, 0.999]
        clipping: 1
        lr: 0.0001
        n_updates: 5
    G:
        betas: [0.5, 0.999]
        clipping: 1
        lr: 0.0001
    shuffle: True
image:
  channels: 3
  height: 128
  width: 128
  labels: [8, 9, 11, 20, 22, 24, 31, 39]
results:
  generated: "../training_examples/img_{}.jpg"
  model: "../saved_model/stargan.pt"